name: Deploy Cloud Run Frontend

on:
  push:
    branches:
      - main  # Or your main branch name
    paths:
      - 'frontend/**'  # Trigger only on changes to the frontend folder

env:
  GCP_REGION: us-central1
  APP_NAME: ccai
  START_TOPIC_ID: start_ccai  
  PORT: 8080 

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Build and push Docker image
        run: |
          echo "Building and pushing Docker image..."
          cd frontend  # Navigate to the frontend directory
          gcloud builds submit --tag ${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/genai/${{ env.APP_NAME }}:v1.0.0
          cd - 

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying to Cloud Run..."
          gcloud run deploy ${{ env.APP_NAME }}-generator \
              --image ${{ env.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/genai/${{ env.APP_NAME }}:v1.0.0 \
              --set-env-vars START_TOPIC_ID=${{ env.START_TOPIC_ID }},PROJECT_ID=${{ secrets.GCP_PROJECT_ID }} \
              --port ${{ env.PORT }} --service-account ${{ secrets.GCP_SA }}  --region ${{ env.GCP_REGION }} --allow-unauthenticated