name: Deploy Cloud Functions

on:
  push:
    branches:
      - main  

env:
  GCP_REGION: us-central1   
  RUNTIME: python311
  START_TOPIC: start_ccai
  TASK_TOPIC: task_ccai
  ZIP_TOPIC: zip_ccai 
  GEMINI_MODEL: gemini-1.5-flash-001
  EXPIRATION_MIN: 260         

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Deploy each function with its specific trigger and env variables
        run: |
          # Zip Task 
          cd backend/zip_task
          gcloud functions deploy zip_ccai_task\
                                  --gen2 \
                                  --max-instances 2 \
                                  --region ${{ env.GCP_REGION }} \
                                  --source . \
                                  --entry-point zip_task \
                                  --runtime ${{ env.RUNTIME }} \
                                  --memory 1Gi \
                                  --timeout 1700 \
                                  --trigger-topic ${{ env.ZIP_TOPIC }} --set-env-vars BUCKET_NAME=${{ secrets.BUCKET_NAME }},PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},FIRESTORE_DB=${{ secrets.FIRESTORE_DB }},KEY_BLOB_NAME=${{ secrets.GCP_SA_KEY }},EXPIRATION_MIN=${{ env.EXPIRATION_MIN }} --service-account=${{ secrets.GCP_SA }} 